server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql:///leyou
    username: root
    password: s814466057
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5  #心跳时间
    lease-expiration-duration-in-seconds: 15 #服务持续时间
mybatis:
  type-aliases-package: com.leyou.item.pojo   # 包扫描的路径